CREATE TABLE COUPON_CATAGORY(
	CATAGORY_NUM NUMBER(2) NOT NULL,
	CATAGORY VARCHAR2(30) NOT NULL,
	CONSTRAINT CATAGORY_PK PRIMARY KEY(CATAGORY_NUM)
);

DROP TABLE COUPON_CATAGORY;

CREATE SEQUENCE COUPON_CATAGOEY_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 99
MINVALUE 1
NOCYCLE;

INSERT INTO HR.COUPON_CATAGORY
(CATAGORY_NUM, CATAGORY)
VALUES(1, '상품권');

INSERT INTO HR.COUPON_CATAGORY
(CATAGORY_NUM, CATAGORY)
VALUES(2, '영화/공연');

INSERT INTO HR.COUPON_CATAGORY
(CATAGORY_NUM, CATAGORY)
VALUES(3, '뷰티');

INSERT INTO HR.COUPON_CATAGORY
(CATAGORY_NUM, CATAGORY)
VALUES(4, '디저트');

INSERT INTO HR.COUPON_CATAGORY
(CATAGORY_NUM, CATAGORY)
VALUES(5, '식사');

INSERT INTO HR.COUPON_CATAGORY
(CATAGORY_NUM, CATAGORY)
VALUES(6, '편의점/마트');

CREATE TABLE COUPON_COUPON_TO_CATAGORY(
	COUPON_PK NUMBER(10) NOT NULL,
	CATAGORY_PK NUMBER(2) NOT NULL,
	CONSTRAINT COUPON_TO_CATAGORY FOREIGN KEY(COUPON_PK) REFERENCES HR.COUPON_COUPON,
	CONSTRAINT CATAGORY_TO_CATAGORY2 FOREIGN KEY(CATAGORY_PK) REFERENCES HR.COUPON_CATAGORY
);


CREATE TABLE COUPON_USER_TO_CATAGORY(
	USER_PK VARCHAR2(50) NOT NULL,
	CATAGORY_PK NUMBER(2) NOT NULL,
	CONSTRAINT USER_TO_CATAGORY FOREIGN KEY(USER_PK) REFERENCES HR.COUPON_USER,
	CONSTRAINT CATAGORY_TO_CATAGORY FOREIGN KEY(CATAGORY_PK) REFERENCES HR.COUPON_CATAGORY
);
