CREATE TABLE COUPON_COMMENT(
	COMMENT_NUM NUMBER(10) NOT NULL,
	COMMENT_USER VARCHAR2(50) NOT NULL,
	COMMENT_COUPON NUMBER(10) NOT NULL,
	COMMENT_TEXT VARCHAR2(1000) NOT NULL,
	COMMENT_DATETIME DATE DEFAULT SYSDATE,
	IS_DELETED NUMBER(1) DEFAULT 0 CONSTRAINT IS_DELETED CHECK(IS_DELETED = 0 OR IS_DELETED = 1),
	IS_SECRET NUMBER(1) DEFAULT 0 CONSTRAINT IS_SECRET CHECK(IS_SECRET = 0 OR IS_SECRET = 1),
	CONSTRAINT COMMENT_PK PRIMARY KEY(COMMENT_NUM),
	CONSTRAINT COMMENT_TO_USER FOREIGN KEY(COMMENT_USER) REFERENCES HR.COUPON_USER,
	CONSTRAINT COMMENT_TO_COUPON FOREIGN KEY(COMMENT_COUPON) REFERENCES HR.COUPON_COUPON
);

CREATE SEQUENCE COUPON_COMMENT_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
MINVALUE 1
NOCYCLE;

SELECT COUPON_COMMENT_SEQ.CURRVAL FROM DUAL;
SELECT COUPON_COMMENT_SEQ.NEXTVAL FROM DUAL;


