CREATE TABLE COUPON_COUPON(
	COUPON_NUM NUMBER(10) NOT NULL,
	COUPON_NAME VARCHAR2(100) NOT NULL,
	CONPON_SERIAL VARCHAR2(100),
	COUPON_IMAGE VARCHAR2(1000),
	COUPON_DESCRIPTION VARCHAR2(2000) NOT NULL,
	COUPON_PRICE NUMBER(10) DEFAULT 0,
	COUPON_TYPE VARCHAR2(50) CONSTRAINT COUPON_TYPE_SELECTION CHECK(COUPON_TYPE = 'KAKAO' OR COUPON_TYPE = 'BOOK' OR COUPON_TYPE = 'CULTURE'),
	COUPON_OWNER VARCHAR2(50) NOT NULL,
	COUPON_BUYER VARCHAR2(50),
	IS_COUPON_FINISHED NUMBER(1) DEFAULT 0 CONSTRAINT IS_COUPON_FINISHED CHECK(IS_COUPON_FINISHED = 0 OR IS_COUPON_FINISHED = 1),
	IS_COUPON_DETERMINED NUMBER(1) DEFAULT 0 CONSTRAINT IS_COUPON_DETERMINED CHECK(IS_COUPON_DETERMINED = 0 OR IS_COUPON_DETERMINED = 1),
	IS_COUPON_CHEATED NUMBER(1) DEFAULT 0 CONSTRAINT IS_COUPON_CHEATED CHECK(IS_COUPON_CHEATED = 0 OR IS_COUPON_CHEATED = 1),
	COUPON_FINISH_DATE DATE NOT NULL,
	CONSTRAINT COUPON_PK PRIMARY KEY(COUPON_NUM),
	CONSTRAINT COUPON_TO_OWNER FOREIGN KEY(COUPON_OWNER) REFERENCES HR.COUPON_USER,
	CONSTRAINT COUPON_TO_BUYER FOREIGN KEY(COUPON_BUYER) REFERENCES HR.COUPON_USER
);

CREATE SEQUENCE COUPON_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
MINVALUE 1
NOCYCLE;

DROP TABLE COUPON_COUPON;