CREATE TABLE COUPON_COUPON(
	COUPON_NUM NUMBER(10) NOT NULL,
	COUPON_NAME VARCHAR2(100) NOT NULL,
	CONPON_SERIAL VARCHAR2(100),
	COUPON_IMAGE VARCHAR2(1000),
	COUPON_DESCRIPTION VARCHAR2(2000) NOT NULL,
	COUPON_PRICE NUMBER(10) DEFAULT 0,
	COUPON_TYPE VARCHAR2(50) CONSTRAINT COUPON_TYPE_SELECTION CHECK(COUPON_TYPE = '카카오기프티콘' OR COUPON_TYPE = '도서문화상품권' OR COUPON_TYPE = '컬쳐랜드문화상품권'),
	COUPON_OWNER VARCHAR2(50) NOT NULL,
	COUPON_BUYER VARCHAR2(50),
	COUPON_FINISH_DATE DATE NOT NULL,
	CONSTRAINT COUPON_PK PRIMARY KEY(COUPON_NUM),
	CONSTRAINT COUPON_TO_OWNER FOREIGN KEY(COUPON_OWNER) REFERENCES HR.COUPON_USER,
	CONSTRAINT COUPON_TO_BUYER FOREIGN KEY(COUPON_BUYER) REFERENCES HR.COUPON_USER
);

CREATE SEQUENCE COUPON_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
MINVALUE 1
NOCYCLE;