CREATE TABLE COUPON_REVIEW(
	REVIEW_TO VARCHAR2(50) NOT NULL,
	REVIEW_FROM VARCHAR2(50) NOT NULL,
	ELEMENT_1 NUMBER(2) DEFAULT 10 CHECK(ELEMENT_1 BETWEEN 0 AND 10),
	ELEMENT_2 NUMBER(2) DEFAULT 10 CHECK(ELEMENT_2 BETWEEN 0 AND 10),
	ELEMENT_3 NUMBER(2) DEFAULT 10 CHECK(ELEMENT_3 BETWEEN 0 AND 10),
	ELEMENT_4 NUMBER(2) DEFAULT 10 CHECK(ELEMENT_4 BETWEEN 0 AND 10),
	ELEMENT_5 NUMBER(2) DEFAULT 10 CHECK(ELEMENT_5 BETWEEN 0 AND 10),
	CONSTRAINT REVIEW_TO FOREIGN KEY(REVIEW_TO) REFERENCES HR.COUPON_USER,
	CONSTRAINT REVIEW_FROM FOREIGN KEY(REVIEW_FROM) REFERENCES HR.COUPON_USER 
);