CREATE TABLE COUPON_REVIEW(
	REVIEW_TO VARCHAR2(50) NOT NULL,
	REVIEW_FROM VARCHAR2(50) NOT NULL,
	REVIEW NUMBER(2) DEFAULT 10 CHECK(REVIEW BETWEEN 1 AND 10),
	CONSTRAINT REVIEW_TO FOREIGN KEY(REVIEW_TO) REFERENCES HR.COUPON_USER,
	CONSTRAINT REVIEW_FROM FOREIGN KEY(REVIEW_FROM) REFERENCES HR.COUPON_USER 
);

DROP TABLE COUPON_REVIEW;