CREATE TABLE COUPON_TRADE(
	TRADE_NUM NUMBER(10) NOT NULL,
	TRADE_COUPON NUMBER(10) NOT NULL,
	TRADE_BUYER VARCHAR2(50) NOT NULL,
	TRADE_DATE DATE DEFAULT SYSDATE,
	IS_FINISHED NUMBER(1) DEFAULT 0 CONSTRAINT BOOLEAN_IS_FINISHED CHECK(IS_FINISHED = 0 OR IS_FINISHED = 1),
	IS_DETERMINED NUMBER(1) DEFAULT 0 CONSTRAINT BOOLEAN_IS_DETERMINED CHECK(IS_DETERMINED = 0 OR IS_DETERMINED = 1),
	IS_CHEATED NUMBER(1) DEFAULT 0 CONSTRAINT BOOLEAN_IS_CHEATED CHECK(IS_CHEATED = 0 OR IS_CHEATED = 1),
	CONSTRAINT TRADE_PK PRIMARY KEY(TRADE_NUM),
	CONSTRAINT TRADE_TO_BUYER FOREIGN KEY(TRADE_BUYER) REFERENCES HR.COUPON_USER,
	CONSTRAINT TRADE_TO_COUPON FOREIGN KEY(TRADE_COUPON) REFERENCES HR.COUPON_COUPON
);

CREATE SEQUENCE COUPON_TRADE_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 9999999999
MINVALUE 1
NOCYCLE;
