CREATE TABLE COUPON_USER(
	USERNAME VARCHAR2(50) NOT NULL,
	EMAIL VARCHAR2(100) NOT NULL,
	PASSWORD VARCHAR2(100),
	PROFILE_IMAGE VARCHAR2(1000),
	MONEY NUMBER(10) DEFAULT 10000,
	LOGIN_METHOD VARCHAR2(30) DEFAULT 'LOCAL' CONSTRAINT LOGIN_METHOD_SELECT CHECK (LOGIN_METHOD = 'LOCAL' OR LOGIN_METHOD = 'KAKAO' OR LOGIN_METHOD = 'GOOGLE' OR LOGIN_METHOD = 'GITHUB'),
	EMAIL_SECRET VARCHAR2(50),
	EMAIL_VALID NUMBER(1) DEFAULT 0 CONSTRAINT BOOLEAN_EMAIL_VALID CHECK(EMAIL_VALID = 0 OR EMAIL_VALID = 1),
	IS_ACTIVATED NUMBER(1) DEFAULT 1 CONSTRAINT BOOLEAN_IS_ACTIVATED CHECK(IS_ACTIVATED = 0 OR IS_ACTIVATED = 1),
	IS_ADMIN NUMBER(1) DEFAULT 0 CONSTRAINT BOOLEAN_IS_ADMIN CHECK(IS_ADMIN = 0 OR IS_ADMIN = 1),
	IS_EMAIL_PUBLIC NUMBER(1) DEFAULT 1 CONSTRAINT BOOLEAN_IS_EMAIL_PUBLIC CHECK(IS_EMAIL_PUBLIC = 0 OR IS_EMAIL_PUBLIC = 1),
	IS_INTEREST_PUBLIC NUMBER(1) DEFAULT 1 CONSTRAINT BOOLEAN_IS_INTEREST_PUBLIC CHECK(IS_INTEREST_PUBLIC = 0 OR IS_INTEREST_PUBLIC = 1),
	IS_MONEY_PUBLIC NUMBER(1) DEFAULT 1 CONSTRAINT BOOLEAN_IS_MONEY_PUBLIC CHECK(IS_MONEY_PUBLIC = 0 OR IS_MONEY_PUBLIC = 1),
	CONSTRAINT COUPON_USER_PK PRIMARY KEY(EMAIL)
);

DROP TABLE COUPON_USER;

DELETE FROM HR.COUPON_USER
WHERE EMAIL='7cmdehdrb@naver.com';
